name: Code Format
on:
  workflow_call:
  workflow_dispatch:
jobs:
  format:
    name: Code Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        run: scripts/install_tools_apt.sh

      - name: Format source files
        run: cmake -P scripts/code_format.cmake

      - name: Check if formatting changes were required
        id: check
        run: git diff --exit-code >changes.diff

      - name: Add changes to summary
        if: always() && steps.check.outcome == 'failure'
        run: |
          echo "# Changes required" >$GITHUB_STEP_SUMMARY
          echo '```'               >>$GITHUB_STEP_SUMMARY
          cat changes.diff         >>$GITHUB_STEP_SUMMARY
          echo '```'               >>$GITHUB_STEP_SUMMARY

